apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  type: LoadBalancer # This maps the cluster port to your Mac's localhost
  selector:
    app: react-web
  ports:
    - protocol: TCP
      port: 80 # Port the service listens on
      targetPort: 80 # Port the container is listening on
